#!/usr/bin/env bash
# Installs and configures HAProxy

apt-get -y update
apt-get -y install haproxy

cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend www
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 100.53.75.208:80 check
    server web-02 100.26.203.248:80 check
EOF

service haproxy restart
