#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy to send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm

sudo apt-get -y update
sudo apt-get -y install haproxy

echo \
"
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend

backend lb-backend
        balance roundrobin
        server web-01 100.53.75.208:80 check
        server web-02 100.26.203.248:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
