#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me with 301 status

apt-get update -y
apt-get install -y nginx -y

# Add the redirect location
sed -i '/location \/ {/a \\n\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Test configuration
nginx -t

# Restart Nginx
service nginx restart
