#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me with 301 status

apt-get update -y
apt-get install -y nginx -y

cat > /etc/nginx/sites-available/default << 'EOT'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOT

nginx -t
service nginx restart
